################################################################################
# Build-Installer.ps1
#
# Regenerates Distributable\AutoNAV-Installer.cmd - a single-file, double-click,
# self-elevating installer for AutoNAV.  Run this on a Windows machine after
# rebuilding AutoNAV.dll.
#
# Inputs (must sit next to this script):
#   - AutoNAV.dll
#   - AutoNAV.addin
#
# Output:
#   - AutoNAV-Installer.cmd  (single file, distribute as-is to coworkers)
#
# The output .cmd:
#   1. Self-elevates via UAC on double-click.
#   2. Carries AutoNAV.dll + AutoNAV.addin embedded as base64.
#   3. Decodes them to a temp folder.
#   4. Detects installed Navisworks Manage versions (2024-2027) and copies the
#      plugin payload into each version's
#      C:\ProgramData\Autodesk\Navisworks Manage <year>\Plugins\AutoNAV\ folder.
#   5. Cleans up temp files and pauses for the user to read the result.
################################################################################

[CmdletBinding()]
param(
    [string]$SourceDir   = $PSScriptRoot,
    [string]$OutputFile  = (Join-Path $PSScriptRoot 'AutoNAV-Installer.cmd')
)

$ErrorActionPreference = 'Stop'

$dllPath   = Join-Path $SourceDir 'AutoNAV.dll'
$addinPath = Join-Path $SourceDir 'AutoNAV.addin'

foreach ($p in @($dllPath, $addinPath)) {
    if (-not (Test-Path -LiteralPath $p)) {
        throw "Missing input file: $p"
    }
}

function ConvertTo-WrappedBase64([string]$Path, [int]$LineWidth = 76) {
    $bytes = [IO.File]::ReadAllBytes($Path)
    $b64   = [Convert]::ToBase64String($bytes)
    $sb    = New-Object Text.StringBuilder
    for ($i = 0; $i -lt $b64.Length; $i += $LineWidth) {
        $end = [Math]::Min($LineWidth, $b64.Length - $i)
        [void]$sb.AppendLine($b64.Substring($i, $end))
    }
    return $sb.ToString().TrimEnd()
}

$dllB64   = ConvertTo-WrappedBase64 -Path $dllPath
$addinB64 = ConvertTo-WrappedBase64 -Path $addinPath

# .cmd template.  Placeholders ##DLL_B64## and ##ADDIN_B64## are replaced below.
# The block between ##PS_BEGIN## and ##PS_END## is the PowerShell installer; cmd
# never reaches it (the `goto :START` on line 2 jumps past).
$template = @'
@echo off
goto :START

::====================================================================
:: AutoNAV All-in-One Installer  -  v3.0.0
:: Generated by Distributable\Build-Installer.ps1
:: Targets: Navisworks Manage 2024 / 2025 / 2026 / 2027
::
:: This single .cmd file carries AutoNAV.dll and AutoNAV.addin embedded
:: as base64.  Double-click to install.  Admin elevation is requested
:: automatically.  Re-running is safe: existing files are backed up.
::====================================================================

##PS_BEGIN##
$ErrorActionPreference = 'Stop'

# === Embedded payload (do NOT edit by hand; regenerate via Build-Installer.ps1) ===
$AutoNAVDll_b64 = @"
##DLL_B64##
"@

$AutoNAVAddin_b64 = @"
##ADDIN_B64##
"@

$SupportedVersions = @('2024','2025','2026','2027')

function Get-NavisworksInstallDir([string]$Version) {
    foreach ($p in @(
        "C:\Program Files\Autodesk\Navisworks Manage $Version",
        "C:\Program Files (x86)\Autodesk\Navisworks Manage $Version"
    )) {
        if (Test-Path -LiteralPath $p) { return $p }
    }
    return $null
}

function Install-ToVersion([string]$Version, [string]$DllPath, [string]$AddinPath) {
    if (-not (Get-NavisworksInstallDir $Version)) {
        Write-Host "  [--] Navisworks $Version -- not installed, skipped" -ForegroundColor DarkYellow
        return $false
    }
    $dest = "C:\ProgramData\Autodesk\Navisworks Manage $Version\Plugins\AutoNAV"
    if (-not (Test-Path -LiteralPath $dest)) {
        New-Item -ItemType Directory -Path $dest -Force | Out-Null
    }
    $destDll   = Join-Path $dest 'AutoNAV.dll'
    $destAddin = Join-Path $dest 'AutoNAV.addin'
    if ((Test-Path $destDll) -or (Test-Path $destAddin)) {
        $backupDir = Join-Path $dest ("Backup_" + (Get-Date -Format 'yyyyMMdd_HHmmss'))
        New-Item -ItemType Directory -Path $backupDir -Force | Out-Null
        if (Test-Path $destDll)   { Copy-Item $destDll   $backupDir -Force }
        if (Test-Path $destAddin) { Copy-Item $destAddin $backupDir -Force }
        Write-Host "      Backup saved to: $backupDir" -ForegroundColor DarkGray
    }
    Copy-Item $DllPath   $destDll   -Force
    Copy-Item $AddinPath $destAddin -Force
    $sz = [math]::Round((Get-Item $destDll).Length / 1KB, 1)
    Write-Host "  [+] Navisworks $Version -- installed ($sz KB) -> $dest" -ForegroundColor Green
    return $true
}

Write-Host ''
Write-Host '====================================================================='
Write-Host '              AutoNAV All-in-One Installer  v3.0.0'
Write-Host '         Targets: Navisworks Manage 2024 / 2025 / 2026 / 2027'
Write-Host '====================================================================='
Write-Host ''

# Close Navisworks if it's running so the DLL isn't locked
$proc = Get-Process -Name 'Roamer','Navisworks*' -ErrorAction SilentlyContinue
if ($proc) {
    Write-Host 'Closing Navisworks...' -ForegroundColor Yellow
    $proc | Stop-Process -Force -ErrorAction SilentlyContinue
    Start-Sleep -Seconds 2
}

# Decode payload to a temp folder, install, then clean up
$tmpRoot = Join-Path $env:TEMP ('AutoNAV_Installer_' + [Guid]::NewGuid().Guid.Substring(0,8))
New-Item -ItemType Directory -Path $tmpRoot -Force | Out-Null
$installed = @()
try {
    $dllPath   = Join-Path $tmpRoot 'AutoNAV.dll'
    $addinPath = Join-Path $tmpRoot 'AutoNAV.addin'
    [IO.File]::WriteAllBytes($dllPath,   [Convert]::FromBase64String(($AutoNAVDll_b64   -replace '\s','')))
    [IO.File]::WriteAllBytes($addinPath, [Convert]::FromBase64String(($AutoNAVAddin_b64 -replace '\s','')))

    foreach ($v in $SupportedVersions) {
        try {
            if (Install-ToVersion -Version $v -DllPath $dllPath -AddinPath $addinPath) {
                $installed += $v
            }
        } catch {
            Write-Host "  [!] Navisworks $v -- ERROR: $_" -ForegroundColor Red
        }
    }
} finally {
    Remove-Item $tmpRoot -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host ''
Write-Host '====================================================================='
if ($installed.Count -gt 0) {
    Write-Host (" Installation complete!  Installed to: Navisworks " + ($installed -join ', ')) -ForegroundColor Green
    Write-Host ''
    Write-Host ' Next steps:' -ForegroundColor Cyan
    Write-Host '   1. Launch Navisworks Manage'
    Write-Host '   2. Open the Add-Ins ribbon tab'
    Write-Host '   3. Click AutoNAV to begin'
} else {
    Write-Host ' ERROR: No compatible Navisworks installation found.' -ForegroundColor Red
    Write-Host ' Install Navisworks Manage 2024, 2025, 2026, or 2027 and run again.'
}
Write-Host '====================================================================='
Write-Host ''
##PS_END##

:START
setlocal enabledelayedexpansion

REM ----- Self-elevate to admin -----
net session >nul 2>&1
if errorlevel 1 (
    echo Requesting administrator privileges...
    powershell -NoProfile -Command "Start-Process -FilePath '%~f0' -Verb RunAs"
    exit /b
)

REM ----- Hand off to embedded PowerShell installer -----
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$c = Get-Content -Raw -LiteralPath '%~f0';" ^
  "$m = [regex]::Match($c, '(?s)' + '##' + 'PS_BEGIN' + '##(.*?)' + '##' + 'PS_END' + '##');" ^
  "if (-not $m.Success) { Write-Host 'Installer payload missing.' -ForegroundColor Red; exit 1 };" ^
  "$tmpPs = Join-Path $env:TEMP ('AutoNAV_Inst_' + [Guid]::NewGuid().Guid.Substring(0,8) + '.ps1');" ^
  "[IO.File]::WriteAllText($tmpPs, $m.Groups[1].Value, [Text.Encoding]::UTF8);" ^
  "& powershell -NoProfile -ExecutionPolicy Bypass -File $tmpPs;" ^
  "$ec = $LASTEXITCODE;" ^
  "Remove-Item $tmpPs -Force -ErrorAction SilentlyContinue;" ^
  "exit $ec"

set EC=%errorlevel%
echo.
echo Press any key to close...
pause >nul
endlocal
exit /b %EC%
'@

$cmd = $template.Replace('##DLL_B64##', $dllB64).Replace('##ADDIN_B64##', $addinB64)

# Write with CRLF line endings (Windows .cmd convention)
$cmd = $cmd -replace "`r?`n", "`r`n"
[IO.File]::WriteAllText($OutputFile, $cmd, [Text.UTF8Encoding]::new($false))

$outSize = (Get-Item $OutputFile).Length
Write-Host ("Wrote {0} ({1:N0} bytes)" -f $OutputFile, $outSize) -ForegroundColor Green
Write-Host "  Embedded AutoNAV.dll  : $((Get-Item $dllPath).Length) bytes raw"
Write-Host "  Embedded AutoNAV.addin: $((Get-Item $addinPath).Length) bytes raw"
